[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.docker]
command = ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]
options = ["--ipc=host", "--security-opt", "seccomp=/home/pwuser/app/seccomp_profile.json"] 